/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProblemsImport } from './routes/problems'
import { Route as IndexImport } from './routes/index'
import { Route as ProblemSlugImport } from './routes/problem.$slug'

// Create/Update Routes

const ProblemsRoute = ProblemsImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProblemSlugRoute = ProblemSlugImport.update({
  id: '/problem/$slug',
  path: '/problem/$slug',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/problems': {
      id: '/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof ProblemsImport
      parentRoute: typeof rootRoute
    }
    '/problem/$slug': {
      id: '/problem/$slug'
      path: '/problem/$slug'
      fullPath: '/problem/$slug'
      preLoaderRoute: typeof ProblemSlugImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/problems': typeof ProblemsRoute
  '/problem/$slug': typeof ProblemSlugRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/problems': typeof ProblemsRoute
  '/problem/$slug': typeof ProblemSlugRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/problems': typeof ProblemsRoute
  '/problem/$slug': typeof ProblemSlugRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/problems' | '/problem/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/problems' | '/problem/$slug'
  id: '__root__' | '/' | '/problems' | '/problem/$slug'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProblemsRoute: typeof ProblemsRoute
  ProblemSlugRoute: typeof ProblemSlugRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProblemsRoute: ProblemsRoute,
  ProblemSlugRoute: ProblemSlugRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/problems",
        "/problem/$slug"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/problems": {
      "filePath": "problems.tsx"
    },
    "/problem/$slug": {
      "filePath": "problem.$slug.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
